# Generated by Django 4.1.5 on 2023-01-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_pictures',
            new_name='Customer_Picture',
        ),
    ]
