# Generated by Django 4.1.3 on 2023-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_rename_customer_pictures_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/profile_default_picture.jpg', null=True, upload_to=''),
        ),
    ]
