# Generated by Django 4.1.3 on 2023-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_picture',
            name='price',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='Free', max_length=255),
        ),
    ]
