# Generated by Django 4.1.3 on 2023-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_customer_picture_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_picture',
            name='price',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='Free', max_length=255, null=True),
        ),
    ]
