# Generated by Django 4.1.3 on 2023-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_alter_customer_picture_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_picture',
            name='photo',
            field=models.ImageField(upload_to='static/images/basesite_images'),
        ),
    ]
