# Generated by Django 4.1.3 on 2023-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_alter_customer_picture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_picture',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
