# Generated by Django 4.1.3 on 2023-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_category_alter_customer_picture_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_picture',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
