# Generated by Django 4.1.3 on 2023-04-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_alter_customer_picture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_picture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.category'),
        ),
    ]
