# Generated by Django 4.1.3 on 2023-06-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0012_alter_customer_picture_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_price', models.FloatField(blank=True, max_length=50, null=True)),
                ('discounted_price', models.FloatField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('commenter_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='pictures.customer')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pictures.customer_picture')),
            ],
        ),
    ]
